config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'

  resources :users, only:[:create]
  
  resources :dolists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dolist.rb
class Dolist < ApplicationRecord
    validates :content, presence: true, length: { maximum: 255 }
    validates :status, presence: true, length: { maximum: 18 }
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: {maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    private
    
    
    def require_user_logged_in
        unless logged_in?
            redirect_to login_url
        end
    end
    
    def counts(user)
    @count_dolists = user.dolists.count
    end
end

app/controllers/dolists_controller.rb
class DolistsController < ApplicationController
  before_action :set_dolist, only: [:show, :edit, :update, :destroy]
  
  
  def index
    @dolists = Dolist.order(id: :desc).page(params[:page]).per(24)
  end

  def show
  end

  def new
    @dolist = Dolist.new
  end

  def create
    @dolist = Dolist.new(dolist_params)
      
      if @dolist.save
        flash[:success] = 'Taskが正常に投稿されました'
        redirect_to @dolist
      else
        flash.now[:danger] = 'Taskが投稿されませんでした'
        render :new
      end
  end

  def edit
  end

  def update

    if @dolist.update(dolist_params)
      flash[:success] = 'Task は正常に更新されました'
      redirect_to @dolist
    else
      flash.now[:danger] = 'Task は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @dolist.destroy

    flash[:success] = 'Task は正常に削除されました'
    redirect_to tasks_url
  end
  
  private

  # Strong Parameter
  
  def set_dolist
    @dolist = Dolist.find(params[:id])
  end
  
  
  def dolist_params
    params.require(:dolist).permit(:content, :status)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email =params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
      if @user && @user.authenticate(password)
        
        session[:user_id] = @user.id
        return true
      else
        return false
      end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @dolists = Dolist.order(id: :desc).page(params[:page]).per(24)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmaation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/dolists/_form.html.erb
<div class="row">
  <div class="col-6">
    <%= form_with(model: dolist, local: true) do |f| %>
      <% if dolist.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <ul class="mb-0">
            <% dolist.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :status, 'ステータス' %>
        <%= f.text_field :status, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :content, 'タスク' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>

      <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/dolists/edit.html.erb
<h1>id: <%= @dolist.id %> のタスク編集ページ</h1>

<%= render 'form', dolist: @dolist %>

<%= link_to '一覧に戻る', root_path %>

app/views/dolists/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form', dolist: @dolist %>

app/views/dolists/show.html.erb
<h1>id: <%= @dolist.id %> のタスク詳細ページ</h1>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @dolist.id %></td>
  </tr>
  <tr>
    <th>ステータス</th>
    <td><%= @dolist.status %></td>
  </tr>
  <tr>
    <th>タスク</th>
    <td><%= @dolist.content %></td>
  </tr>
</table>

<%= link_to 'このタスクを編集する', edit_dolist_path(@dolist), class: 'btn btn-light' %>
<%= link_to 'このタスクを削除する', @dolist, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">タスク一覧</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to '新しいタスク', new_dolist_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <!--<li class="dropdown-divider"></li>-->
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <h1>タスク一覧</h1>

<% if @dolists.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>ステータス</th>
        <th>タスク</th>
      </tr>
    </thead>
    <tbody>
      <% @dolists.each do |message| %>
        <tr>
          <td><%= link_to message.id, message %></td>
          <td><%= message.status %></td>
          <td><%= message.content %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate @dolists %>
  </div>
<% end %>

<%= link_to '新規タスクの投稿', new_dolist_path, class: "btn btn-primary" %>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Todolists</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>